#!/usr/bin/env bash

here="$(dirname "$0")"
echo "=>>>>> $here"
echo ">>>>> $@"

set -x
exec cargo run --manifest-path="$here"/Cargo.toml --bin solana-test-validator -- "$@"

# cargo build --release  --manifest-path=./Cargo.toml --bin solana-test-validator
# ./solana-test-validator --ticks-per-slot 2
